{{- if .Values.ingress.enabled -}}
kind: Ingress
metadata:
  name: {{ include "onyx-stack.fullname" . }}-ingress-webserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.webserver.clusterIssuer }}
spec:
  rules:
    - host: {{ .Values.ingress.webserver.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "onyx-stack.fullname" . }}-web-service
                port:
                  number: {{ .Values.webserver.service.servicePort }}
  tls:
    - hosts:
        - {{ .Values.ingress.webserver.host }}
      secretName: {{ include "onyx-stack.fullname" . }}-ingress-webserver-tls
