name: Python Unit Tests

on:
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  check-run-needed:
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.check.outputs.run-tests }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^backend/'; then
            echo "run-tests=true" >> $GITHUB_OUTPUT
          else
            echo "run-tests=false" >> $GITHUB_OUTPUT
          fi

  backend-check:
    needs: check-run-needed
    if: needs.check-run-needed.outputs.run-tests == 'true'
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          backend/requirements/default.txt
          backend/requirements/dev.txt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements/default.txt
        pip install -r backend/requirements/dev.txt

    - name: Run Tests
      shell: script -q -e -c "bash --noprofile --norc -eo pipefail {0}"
      run: py.test -o junit_family=xunit2 -xv --ff backend/tests/unit


  skip-tests:
    needs: check-run-needed
    if: needs.check-run-needed.outputs.run-tests == 'false'
    runs-on: ubuntu-latest
    steps:
      - run: echo "No changes in backend, skipping this test."
